// -------------------------------------------------------------
// 
// File Name: C:\Users\hp\OneDrive\Documents\Mini Project\v4\codegen\svm_inference_hdl_v2\hdlsrc\svm_inference_hdl_v2_fixpt_tb.v
// Created: 2026-02-12 14:54:03
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: svm_inference_hdl_v2_fixpt_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module svm_inference_hdl_v2_fixpt_tb;

  reg  clk;
  reg  reset;
  wire enb;
  wire family_id_done;  // ufix1
  wire rdEnb;
  wire family_id_done_enb;  // ufix1
  reg [2:0] contaminated_addr;  // ufix3
  wire family_id_lastAddr;  // ufix1
  wire resetn;
  reg  check2_done;  // ufix1
  wire contaminated_done;  // ufix1
  wire contaminated_done_enb;  // ufix1
  wire contaminated_active;  // ufix1
  wire snkDone;
  wire snkDonen;
  wire tb_enb;
  wire ce_out;
  wire contaminated_enb;  // ufix1
  wire contaminated_lastAddr;  // ufix1
  reg  check1_done;  // ufix1
  reg [2:0] features_stage1_addr;  // ufix3
  wire features_stage1_active;  // ufix1
  wire features_stage1_enb;  // ufix1
  wire [2:0] features_stage1_addr_delay_1;  // ufix3
  reg signed [31:0] fp_features_stage1_0;  // sfix32
  reg [13:0] rawData_features_stage1_0;  // ufix14
  reg signed [31:0] status_features_stage1_0;  // sfix32
  reg [13:0] holdData_features_stage1_0;  // ufix14
  reg signed [31:0] fp_features_stage1_1;  // sfix32
  reg [13:0] rawData_features_stage1_1;  // ufix14
  reg signed [31:0] status_features_stage1_1;  // sfix32
  reg [13:0] holdData_features_stage1_1;  // ufix14
  reg signed [31:0] fp_features_stage1_2;  // sfix32
  reg [13:0] rawData_features_stage1_2;  // ufix14
  reg signed [31:0] status_features_stage1_2;  // sfix32
  reg [13:0] holdData_features_stage1_2;  // ufix14
  reg signed [31:0] fp_features_stage1_3;  // sfix32
  reg [13:0] rawData_features_stage1_3;  // ufix14
  reg signed [31:0] status_features_stage1_3;  // sfix32
  reg [13:0] holdData_features_stage1_3;  // ufix14
  reg signed [31:0] fp_features_stage1_4;  // sfix32
  reg [13:0] rawData_features_stage1_4;  // ufix14
  reg signed [31:0] status_features_stage1_4;  // sfix32
  reg [13:0] holdData_features_stage1_4;  // ufix14
  reg signed [31:0] fp_features_stage1_5;  // sfix32
  reg [13:0] rawData_features_stage1_5;  // ufix14
  reg signed [31:0] status_features_stage1_5;  // sfix32
  reg [13:0] holdData_features_stage1_5;  // ufix14
  reg signed [31:0] fp_features_stage1_6;  // sfix32
  reg [13:0] rawData_features_stage1_6;  // ufix14
  reg signed [31:0] status_features_stage1_6;  // sfix32
  reg [13:0] holdData_features_stage1_6;  // ufix14
  reg signed [31:0] fp_features_stage1_7;  // sfix32
  reg [13:0] rawData_features_stage1_7;  // ufix14
  reg signed [31:0] status_features_stage1_7;  // sfix32
  reg [13:0] holdData_features_stage1_7;  // ufix14
  reg signed [31:0] fp_features_stage1_8;  // sfix32
  reg [13:0] rawData_features_stage1_8;  // ufix14
  reg signed [31:0] status_features_stage1_8;  // sfix32
  reg [13:0] holdData_features_stage1_8;  // ufix14
  reg signed [31:0] fp_features_stage1_9;  // sfix32
  reg [13:0] rawData_features_stage1_9;  // ufix14
  reg signed [31:0] status_features_stage1_9;  // sfix32
  reg [13:0] holdData_features_stage1_9;  // ufix14
  reg signed [31:0] fp_features_stage1_10;  // sfix32
  reg [13:0] rawData_features_stage1_10;  // ufix14
  reg signed [31:0] status_features_stage1_10;  // sfix32
  reg [13:0] holdData_features_stage1_10;  // ufix14
  reg signed [31:0] fp_features_stage1_11;  // sfix32
  reg [13:0] rawData_features_stage1_11;  // ufix14
  reg signed [31:0] status_features_stage1_11;  // sfix32
  reg [13:0] holdData_features_stage1_11;  // ufix14
  reg signed [31:0] fp_features_stage1_12;  // sfix32
  reg [13:0] rawData_features_stage1_12;  // ufix14
  reg signed [31:0] status_features_stage1_12;  // sfix32
  reg [13:0] holdData_features_stage1_12;  // ufix14
  reg signed [31:0] fp_features_stage1_13;  // sfix32
  reg [13:0] rawData_features_stage1_13;  // ufix14
  reg signed [31:0] status_features_stage1_13;  // sfix32
  reg [13:0] holdData_features_stage1_13;  // ufix14
  reg signed [31:0] fp_features_stage1_14;  // sfix32
  reg [13:0] rawData_features_stage1_14;  // ufix14
  reg signed [31:0] status_features_stage1_14;  // sfix32
  reg [13:0] holdData_features_stage1_14;  // ufix14
  reg signed [31:0] fp_features_stage1_15;  // sfix32
  reg [13:0] rawData_features_stage1_15;  // ufix14
  reg signed [31:0] status_features_stage1_15;  // sfix32
  reg [13:0] holdData_features_stage1_15;  // ufix14
  reg signed [31:0] fp_features_stage1_16;  // sfix32
  reg [13:0] rawData_features_stage1_16;  // ufix14
  reg signed [31:0] status_features_stage1_16;  // sfix32
  reg [13:0] holdData_features_stage1_16;  // ufix14
  reg signed [31:0] fp_features_stage1_17;  // sfix32
  reg [13:0] rawData_features_stage1_17;  // ufix14
  reg signed [31:0] status_features_stage1_17;  // sfix32
  reg [13:0] holdData_features_stage1_17;  // ufix14
  reg signed [31:0] fp_features_stage1_18;  // sfix32
  reg [13:0] rawData_features_stage1_18;  // ufix14
  reg signed [31:0] status_features_stage1_18;  // sfix32
  reg [13:0] holdData_features_stage1_18;  // ufix14
  wire [2:0] features_stage2_addr_delay_1;  // ufix3
  reg signed [31:0] fp_features_stage2_0;  // sfix32
  reg [13:0] rawData_features_stage2_0;  // ufix14
  reg signed [31:0] status_features_stage2_0;  // sfix32
  reg [13:0] holdData_features_stage2_0;  // ufix14
  reg signed [31:0] fp_features_stage2_1;  // sfix32
  reg [13:0] rawData_features_stage2_1;  // ufix14
  reg signed [31:0] status_features_stage2_1;  // sfix32
  reg [13:0] holdData_features_stage2_1;  // ufix14
  reg signed [31:0] fp_features_stage2_2;  // sfix32
  reg [13:0] rawData_features_stage2_2;  // ufix14
  reg signed [31:0] status_features_stage2_2;  // sfix32
  reg [13:0] holdData_features_stage2_2;  // ufix14
  reg signed [31:0] fp_features_stage2_3;  // sfix32
  reg [13:0] rawData_features_stage2_3;  // ufix14
  reg signed [31:0] status_features_stage2_3;  // sfix32
  reg [13:0] holdData_features_stage2_3;  // ufix14
  reg signed [31:0] fp_features_stage2_4;  // sfix32
  reg [13:0] rawData_features_stage2_4;  // ufix14
  reg signed [31:0] status_features_stage2_4;  // sfix32
  reg [13:0] holdData_features_stage2_4;  // ufix14
  reg signed [31:0] fp_features_stage2_5;  // sfix32
  reg [13:0] rawData_features_stage2_5;  // ufix14
  reg signed [31:0] status_features_stage2_5;  // sfix32
  reg [13:0] holdData_features_stage2_5;  // ufix14
  reg signed [31:0] fp_features_stage2_6;  // sfix32
  reg [13:0] rawData_features_stage2_6;  // ufix14
  reg signed [31:0] status_features_stage2_6;  // sfix32
  reg [13:0] holdData_features_stage2_6;  // ufix14
  reg signed [31:0] fp_features_stage2_7;  // sfix32
  reg [13:0] rawData_features_stage2_7;  // ufix14
  reg signed [31:0] status_features_stage2_7;  // sfix32
  reg [13:0] holdData_features_stage2_7;  // ufix14
  reg signed [31:0] fp_features_stage2_8;  // sfix32
  reg [13:0] rawData_features_stage2_8;  // ufix14
  reg signed [31:0] status_features_stage2_8;  // sfix32
  reg [13:0] holdData_features_stage2_8;  // ufix14
  reg signed [31:0] fp_features_stage2_9;  // sfix32
  reg [13:0] rawData_features_stage2_9;  // ufix14
  reg signed [31:0] status_features_stage2_9;  // sfix32
  reg [13:0] holdData_features_stage2_9;  // ufix14
  reg signed [31:0] fp_features_stage2_10;  // sfix32
  reg [13:0] rawData_features_stage2_10;  // ufix14
  reg signed [31:0] status_features_stage2_10;  // sfix32
  reg [13:0] holdData_features_stage2_10;  // ufix14
  reg signed [31:0] fp_features_stage2_11;  // sfix32
  reg [13:0] rawData_features_stage2_11;  // ufix14
  reg signed [31:0] status_features_stage2_11;  // sfix32
  reg [13:0] holdData_features_stage2_11;  // ufix14
  reg signed [31:0] fp_features_stage2_12;  // sfix32
  reg [13:0] rawData_features_stage2_12;  // ufix14
  reg signed [31:0] status_features_stage2_12;  // sfix32
  reg [13:0] holdData_features_stage2_12;  // ufix14
  reg signed [31:0] fp_features_stage2_13;  // sfix32
  reg [13:0] rawData_features_stage2_13;  // ufix14
  reg signed [31:0] status_features_stage2_13;  // sfix32
  reg [13:0] holdData_features_stage2_13;  // ufix14
  reg signed [31:0] fp_features_stage2_14;  // sfix32
  reg [13:0] rawData_features_stage2_14;  // ufix14
  reg signed [31:0] status_features_stage2_14;  // sfix32
  reg [13:0] holdData_features_stage2_14;  // ufix14
  reg signed [31:0] fp_features_stage2_15;  // sfix32
  reg [13:0] rawData_features_stage2_15;  // ufix14
  reg signed [31:0] status_features_stage2_15;  // sfix32
  reg [13:0] holdData_features_stage2_15;  // ufix14
  reg signed [31:0] fp_features_stage2_16;  // sfix32
  reg [13:0] rawData_features_stage2_16;  // ufix14
  reg signed [31:0] status_features_stage2_16;  // sfix32
  reg [13:0] holdData_features_stage2_16;  // ufix14
  reg signed [31:0] fp_features_stage2_17;  // sfix32
  reg [13:0] rawData_features_stage2_17;  // ufix14
  reg signed [31:0] status_features_stage2_17;  // sfix32
  reg [13:0] holdData_features_stage2_17;  // ufix14
  reg signed [31:0] fp_features_stage2_18;  // sfix32
  reg [13:0] rawData_features_stage2_18;  // ufix14
  reg signed [31:0] status_features_stage2_18;  // sfix32
  reg [13:0] holdData_features_stage2_18;  // ufix14
  reg signed [31:0] fp_features_stage2_19;  // sfix32
  reg [13:0] rawData_features_stage2_19;  // ufix14
  reg signed [31:0] status_features_stage2_19;  // sfix32
  reg [13:0] holdData_features_stage2_19;  // ufix14
  reg signed [31:0] fp_features_stage2_20;  // sfix32
  reg [13:0] rawData_features_stage2_20;  // ufix14
  reg signed [31:0] status_features_stage2_20;  // sfix32
  reg [13:0] holdData_features_stage2_20;  // ufix14
  reg signed [31:0] fp_features_stage2_21;  // sfix32
  reg [13:0] rawData_features_stage2_21;  // ufix14
  reg signed [31:0] status_features_stage2_21;  // sfix32
  reg [13:0] holdData_features_stage2_21;  // ufix14
  reg signed [31:0] fp_features_stage2_22;  // sfix32
  reg [13:0] rawData_features_stage2_22;  // ufix14
  reg signed [31:0] status_features_stage2_22;  // sfix32
  reg [13:0] holdData_features_stage2_22;  // ufix14
  reg signed [31:0] fp_features_stage2_23;  // sfix32
  reg [13:0] rawData_features_stage2_23;  // ufix14
  reg signed [31:0] status_features_stage2_23;  // sfix32
  reg [13:0] holdData_features_stage2_23;  // ufix14
  reg signed [31:0] fp_features_stage2_24;  // sfix32
  reg [13:0] rawData_features_stage2_24;  // ufix14
  reg signed [31:0] status_features_stage2_24;  // sfix32
  reg [13:0] holdData_features_stage2_24;  // ufix14
  reg signed [31:0] fp_features_stage2_25;  // sfix32
  reg [13:0] rawData_features_stage2_25;  // ufix14
  reg signed [31:0] status_features_stage2_25;  // sfix32
  reg [13:0] holdData_features_stage2_25;  // ufix14
  reg signed [31:0] fp_features_stage2_26;  // sfix32
  reg [13:0] rawData_features_stage2_26;  // ufix14
  reg signed [31:0] status_features_stage2_26;  // sfix32
  reg [13:0] holdData_features_stage2_26;  // ufix14
  reg signed [31:0] fp_features_stage2_27;  // sfix32
  reg [13:0] rawData_features_stage2_27;  // ufix14
  reg signed [31:0] status_features_stage2_27;  // sfix32
  reg [13:0] holdData_features_stage2_27;  // ufix14
  reg signed [31:0] fp_features_stage2_28;  // sfix32
  reg [13:0] rawData_features_stage2_28;  // ufix14
  reg signed [31:0] status_features_stage2_28;  // sfix32
  reg [13:0] holdData_features_stage2_28;  // ufix14
  reg signed [31:0] fp_features_stage2_29;  // sfix32
  reg [13:0] rawData_features_stage2_29;  // ufix14
  reg signed [31:0] status_features_stage2_29;  // sfix32
  reg [13:0] holdData_features_stage2_29;  // ufix14
  reg signed [31:0] fp_features_stage2_30;  // sfix32
  reg [13:0] rawData_features_stage2_30;  // ufix14
  reg signed [31:0] status_features_stage2_30;  // sfix32
  reg [13:0] holdData_features_stage2_30;  // ufix14
  reg signed [31:0] fp_features_stage2_31;  // sfix32
  reg [13:0] rawData_features_stage2_31;  // ufix14
  reg signed [31:0] status_features_stage2_31;  // sfix32
  reg [13:0] holdData_features_stage2_31;  // ufix14
  reg signed [31:0] fp_features_stage2_32;  // sfix32
  reg [13:0] rawData_features_stage2_32;  // ufix14
  reg signed [31:0] status_features_stage2_32;  // sfix32
  reg [13:0] holdData_features_stage2_32;  // ufix14
  reg signed [31:0] fp_features_stage2_33;  // sfix32
  reg [13:0] rawData_features_stage2_33;  // ufix14
  reg signed [31:0] status_features_stage2_33;  // sfix32
  reg [13:0] holdData_features_stage2_33;  // ufix14
  reg signed [31:0] fp_features_stage2_34;  // sfix32
  reg [13:0] rawData_features_stage2_34;  // ufix14
  reg signed [31:0] status_features_stage2_34;  // sfix32
  reg [13:0] holdData_features_stage2_34;  // ufix14
  reg [13:0] features_stage1_0_offset;  // ufix14
  wire [13:0] features_stage1_0;  // ufix14
  reg [13:0] features_stage1_1_offset;  // ufix14
  wire [13:0] features_stage1_1;  // ufix14
  reg [13:0] features_stage1_2_offset;  // ufix14
  wire [13:0] features_stage1_2;  // ufix14
  reg [13:0] features_stage1_3_offset;  // ufix14
  wire [13:0] features_stage1_3;  // ufix14
  reg [13:0] features_stage1_4_offset;  // ufix14
  wire [13:0] features_stage1_4;  // ufix14
  reg [13:0] features_stage1_5_offset;  // ufix14
  wire [13:0] features_stage1_5;  // ufix14
  reg [13:0] features_stage1_6_offset;  // ufix14
  wire [13:0] features_stage1_6;  // ufix14
  reg [13:0] features_stage1_7_offset;  // ufix14
  wire [13:0] features_stage1_7;  // ufix14
  reg [13:0] features_stage1_8_offset;  // ufix14
  wire [13:0] features_stage1_8;  // ufix14
  reg [13:0] features_stage1_9_offset;  // ufix14
  wire [13:0] features_stage1_9;  // ufix14
  reg [13:0] features_stage1_10_offset;  // ufix14
  wire [13:0] features_stage1_10;  // ufix14
  reg [13:0] features_stage1_11_offset;  // ufix14
  wire [13:0] features_stage1_11;  // ufix14
  reg [13:0] features_stage1_12_offset;  // ufix14
  wire [13:0] features_stage1_12;  // ufix14
  reg [13:0] features_stage1_13_offset;  // ufix14
  wire [13:0] features_stage1_13;  // ufix14
  reg [13:0] features_stage1_14_offset;  // ufix14
  wire [13:0] features_stage1_14;  // ufix14
  reg [13:0] features_stage1_15_offset;  // ufix14
  wire [13:0] features_stage1_15;  // ufix14
  reg [13:0] features_stage1_16_offset;  // ufix14
  wire [13:0] features_stage1_16;  // ufix14
  reg [13:0] features_stage1_17_offset;  // ufix14
  wire [13:0] features_stage1_17;  // ufix14
  reg [13:0] features_stage1_18_offset;  // ufix14
  wire [13:0] features_stage1_18;  // ufix14
  reg [13:0] features_stage2_0_offset;  // ufix14
  wire [13:0] features_stage2_0;  // ufix14
  reg [13:0] features_stage2_1_offset;  // ufix14
  wire [13:0] features_stage2_1;  // ufix14
  reg [13:0] features_stage2_2_offset;  // ufix14
  wire [13:0] features_stage2_2;  // ufix14
  reg [13:0] features_stage2_3_offset;  // ufix14
  wire [13:0] features_stage2_3;  // ufix14
  reg [13:0] features_stage2_4_offset;  // ufix14
  wire [13:0] features_stage2_4;  // ufix14
  reg [13:0] features_stage2_5_offset;  // ufix14
  wire [13:0] features_stage2_5;  // ufix14
  reg [13:0] features_stage2_6_offset;  // ufix14
  wire [13:0] features_stage2_6;  // ufix14
  reg [13:0] features_stage2_7_offset;  // ufix14
  wire [13:0] features_stage2_7;  // ufix14
  reg [13:0] features_stage2_8_offset;  // ufix14
  wire [13:0] features_stage2_8;  // ufix14
  reg [13:0] features_stage2_9_offset;  // ufix14
  wire [13:0] features_stage2_9;  // ufix14
  reg [13:0] features_stage2_10_offset;  // ufix14
  wire [13:0] features_stage2_10;  // ufix14
  reg [13:0] features_stage2_11_offset;  // ufix14
  wire [13:0] features_stage2_11;  // ufix14
  reg [13:0] features_stage2_12_offset;  // ufix14
  wire [13:0] features_stage2_12;  // ufix14
  reg [13:0] features_stage2_13_offset;  // ufix14
  wire [13:0] features_stage2_13;  // ufix14
  reg [13:0] features_stage2_14_offset;  // ufix14
  wire [13:0] features_stage2_14;  // ufix14
  reg [13:0] features_stage2_15_offset;  // ufix14
  wire [13:0] features_stage2_15;  // ufix14
  reg [13:0] features_stage2_16_offset;  // ufix14
  wire [13:0] features_stage2_16;  // ufix14
  reg [13:0] features_stage2_17_offset;  // ufix14
  wire [13:0] features_stage2_17;  // ufix14
  reg [13:0] features_stage2_18_offset;  // ufix14
  wire [13:0] features_stage2_18;  // ufix14
  reg [13:0] features_stage2_19_offset;  // ufix14
  wire [13:0] features_stage2_19;  // ufix14
  reg [13:0] features_stage2_20_offset;  // ufix14
  wire [13:0] features_stage2_20;  // ufix14
  reg [13:0] features_stage2_21_offset;  // ufix14
  wire [13:0] features_stage2_21;  // ufix14
  reg [13:0] features_stage2_22_offset;  // ufix14
  wire [13:0] features_stage2_22;  // ufix14
  reg [13:0] features_stage2_23_offset;  // ufix14
  wire [13:0] features_stage2_23;  // ufix14
  reg [13:0] features_stage2_24_offset;  // ufix14
  wire [13:0] features_stage2_24;  // ufix14
  reg [13:0] features_stage2_25_offset;  // ufix14
  wire [13:0] features_stage2_25;  // ufix14
  reg [13:0] features_stage2_26_offset;  // ufix14
  wire [13:0] features_stage2_26;  // ufix14
  reg [13:0] features_stage2_27_offset;  // ufix14
  wire [13:0] features_stage2_27;  // ufix14
  reg [13:0] features_stage2_28_offset;  // ufix14
  wire [13:0] features_stage2_28;  // ufix14
  reg [13:0] features_stage2_29_offset;  // ufix14
  wire [13:0] features_stage2_29;  // ufix14
  reg [13:0] features_stage2_30_offset;  // ufix14
  wire [13:0] features_stage2_30;  // ufix14
  reg [13:0] features_stage2_31_offset;  // ufix14
  wire [13:0] features_stage2_31;  // ufix14
  reg [13:0] features_stage2_32_offset;  // ufix14
  wire [13:0] features_stage2_32;  // ufix14
  reg [13:0] features_stage2_33_offset;  // ufix14
  wire [13:0] features_stage2_33;  // ufix14
  reg [13:0] features_stage2_34_offset;  // ufix14
  wire [13:0] features_stage2_34;  // ufix14
  wire contaminated_1;  // ufix1
  wire [2:0] family_id;  // ufix3
  wire contaminated_expected_1;  // ufix1
  wire contaminated_ref;  // ufix1
  reg  contaminated_testFailure;  // ufix1
  wire [2:0] family_id_expected_1;  // ufix3
  wire [2:0] family_id_ref;  // ufix3
  reg  family_id_testFailure;  // ufix1
  wire testFailure;  // ufix1


  assign family_id_done_enb = family_id_done & rdEnb;

  assign family_id_lastAddr = contaminated_addr >= 3'b101;

  assign family_id_done = family_id_lastAddr & resetn;

  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_2
      if (reset) begin
        check2_done <= 0;
      end
      else begin
        if (family_id_done_enb) begin
          check2_done <= family_id_done;
        end
      end
    end

  assign contaminated_done_enb = contaminated_done & rdEnb;

  assign contaminated_active = contaminated_addr != 3'b101;

  assign #2 enb = rdEnb;

  assign snkDonen =  ~ snkDone;

  always 
    begin : clk_gen
      clk <= 1'b1;
      # (5);
      clk <= 1'b0;
      # (5);
      if (snkDone == 1'b1) begin
        clk <= 1'b1;
        # (5);
        clk <= 1'b0;
        # (5);
        $stop;
      end
    end

  initial
    begin : reset_gen
      reset <= 1'b1;
      # (20);
      @ (posedge clk)
      # (2);
      reset <= 1'b0;
    end

  assign resetn =  ~ reset;

  assign tb_enb = resetn & snkDonen;

  assign rdEnb = (snkDone == 1'b0 ? tb_enb :
              1'b0);

  assign ce_out = enb & (rdEnb & tb_enb);

  assign contaminated_enb = ce_out & contaminated_active;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 5
  always @(posedge clk or posedge reset)
    begin : contaminated_process
      if (reset == 1'b1) begin
        contaminated_addr <= 3'b000;
      end
      else begin
        if (contaminated_enb) begin
          if (contaminated_addr >= 3'b101) begin
            contaminated_addr <= 3'b000;
          end
          else begin
            contaminated_addr <= contaminated_addr + 3'b001;
          end
        end
      end
    end

  assign contaminated_lastAddr = contaminated_addr >= 3'b101;

  assign contaminated_done = contaminated_lastAddr & resetn;

  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_1
      if (reset) begin
        check1_done <= 0;
      end
      else begin
        if (contaminated_done_enb) begin
          check1_done <= contaminated_done;
        end
      end
    end

  assign snkDone = check1_done & check2_done;

  assign features_stage1_active = features_stage1_addr != 3'b101;

  assign features_stage1_enb = features_stage1_active & (rdEnb & tb_enb);

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 5
  always @(posedge clk or posedge reset)
    begin : features_stage1_process
      if (reset == 1'b1) begin
        features_stage1_addr <= 3'b000;
      end
      else begin
        if (features_stage1_enb) begin
          if (features_stage1_addr >= 3'b101) begin
            features_stage1_addr <= 3'b000;
          end
          else begin
            features_stage1_addr <= features_stage1_addr + 3'b001;
          end
        end
      end
    end

  assign #1 features_stage1_addr_delay_1 = features_stage1_addr;

  // Data source for features_stage1_0
  initial
    begin : features_stage1_0_fileread
      fp_features_stage1_0 = $fopen("features_stage1_0.dat", "r");
      status_features_stage1_0 = $rewind(fp_features_stage1_0);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_0 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_0 = $fscanf(fp_features_stage1_0, "%h", rawData_features_stage1_0);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1
      if (reset) begin
        holdData_features_stage1_0 <= 14'bx;
      end
      else begin
        holdData_features_stage1_0 <= rawData_features_stage1_0;
      end
    end

  // Data source for features_stage1_1
  initial
    begin : features_stage1_1_fileread
      fp_features_stage1_1 = $fopen("features_stage1_1.dat", "r");
      status_features_stage1_1 = $rewind(fp_features_stage1_1);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_1 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_1 = $fscanf(fp_features_stage1_1, "%h", rawData_features_stage1_1);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_1
      if (reset) begin
        holdData_features_stage1_1 <= 14'bx;
      end
      else begin
        holdData_features_stage1_1 <= rawData_features_stage1_1;
      end
    end

  // Data source for features_stage1_2
  initial
    begin : features_stage1_2_fileread
      fp_features_stage1_2 = $fopen("features_stage1_2.dat", "r");
      status_features_stage1_2 = $rewind(fp_features_stage1_2);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_2 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_2 = $fscanf(fp_features_stage1_2, "%h", rawData_features_stage1_2);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_2
      if (reset) begin
        holdData_features_stage1_2 <= 14'bx;
      end
      else begin
        holdData_features_stage1_2 <= rawData_features_stage1_2;
      end
    end

  // Data source for features_stage1_3
  initial
    begin : features_stage1_3_fileread
      fp_features_stage1_3 = $fopen("features_stage1_3.dat", "r");
      status_features_stage1_3 = $rewind(fp_features_stage1_3);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_3 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_3 = $fscanf(fp_features_stage1_3, "%h", rawData_features_stage1_3);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_3
      if (reset) begin
        holdData_features_stage1_3 <= 14'bx;
      end
      else begin
        holdData_features_stage1_3 <= rawData_features_stage1_3;
      end
    end

  // Data source for features_stage1_4
  initial
    begin : features_stage1_4_fileread
      fp_features_stage1_4 = $fopen("features_stage1_4.dat", "r");
      status_features_stage1_4 = $rewind(fp_features_stage1_4);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_4 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_4 = $fscanf(fp_features_stage1_4, "%h", rawData_features_stage1_4);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_4
      if (reset) begin
        holdData_features_stage1_4 <= 14'bx;
      end
      else begin
        holdData_features_stage1_4 <= rawData_features_stage1_4;
      end
    end

  // Data source for features_stage1_5
  initial
    begin : features_stage1_5_fileread
      fp_features_stage1_5 = $fopen("features_stage1_5.dat", "r");
      status_features_stage1_5 = $rewind(fp_features_stage1_5);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_5 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_5 = $fscanf(fp_features_stage1_5, "%h", rawData_features_stage1_5);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_5
      if (reset) begin
        holdData_features_stage1_5 <= 14'bx;
      end
      else begin
        holdData_features_stage1_5 <= rawData_features_stage1_5;
      end
    end

  // Data source for features_stage1_6
  initial
    begin : features_stage1_6_fileread
      fp_features_stage1_6 = $fopen("features_stage1_6.dat", "r");
      status_features_stage1_6 = $rewind(fp_features_stage1_6);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_6 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_6 = $fscanf(fp_features_stage1_6, "%h", rawData_features_stage1_6);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_6
      if (reset) begin
        holdData_features_stage1_6 <= 14'bx;
      end
      else begin
        holdData_features_stage1_6 <= rawData_features_stage1_6;
      end
    end

  // Data source for features_stage1_7
  initial
    begin : features_stage1_7_fileread
      fp_features_stage1_7 = $fopen("features_stage1_7.dat", "r");
      status_features_stage1_7 = $rewind(fp_features_stage1_7);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_7 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_7 = $fscanf(fp_features_stage1_7, "%h", rawData_features_stage1_7);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_7
      if (reset) begin
        holdData_features_stage1_7 <= 14'bx;
      end
      else begin
        holdData_features_stage1_7 <= rawData_features_stage1_7;
      end
    end

  // Data source for features_stage1_8
  initial
    begin : features_stage1_8_fileread
      fp_features_stage1_8 = $fopen("features_stage1_8.dat", "r");
      status_features_stage1_8 = $rewind(fp_features_stage1_8);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_8 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_8 = $fscanf(fp_features_stage1_8, "%h", rawData_features_stage1_8);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_8
      if (reset) begin
        holdData_features_stage1_8 <= 14'bx;
      end
      else begin
        holdData_features_stage1_8 <= rawData_features_stage1_8;
      end
    end

  // Data source for features_stage1_9
  initial
    begin : features_stage1_9_fileread
      fp_features_stage1_9 = $fopen("features_stage1_9.dat", "r");
      status_features_stage1_9 = $rewind(fp_features_stage1_9);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_9 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_9 = $fscanf(fp_features_stage1_9, "%h", rawData_features_stage1_9);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_9
      if (reset) begin
        holdData_features_stage1_9 <= 14'bx;
      end
      else begin
        holdData_features_stage1_9 <= rawData_features_stage1_9;
      end
    end

  // Data source for features_stage1_10
  initial
    begin : features_stage1_10_fileread
      fp_features_stage1_10 = $fopen("features_stage1_10.dat", "r");
      status_features_stage1_10 = $rewind(fp_features_stage1_10);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_10 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_10 = $fscanf(fp_features_stage1_10, "%h", rawData_features_stage1_10);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_10
      if (reset) begin
        holdData_features_stage1_10 <= 14'bx;
      end
      else begin
        holdData_features_stage1_10 <= rawData_features_stage1_10;
      end
    end

  // Data source for features_stage1_11
  initial
    begin : features_stage1_11_fileread
      fp_features_stage1_11 = $fopen("features_stage1_11.dat", "r");
      status_features_stage1_11 = $rewind(fp_features_stage1_11);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_11 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_11 = $fscanf(fp_features_stage1_11, "%h", rawData_features_stage1_11);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_11
      if (reset) begin
        holdData_features_stage1_11 <= 14'bx;
      end
      else begin
        holdData_features_stage1_11 <= rawData_features_stage1_11;
      end
    end

  // Data source for features_stage1_12
  initial
    begin : features_stage1_12_fileread
      fp_features_stage1_12 = $fopen("features_stage1_12.dat", "r");
      status_features_stage1_12 = $rewind(fp_features_stage1_12);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_12 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_12 = $fscanf(fp_features_stage1_12, "%h", rawData_features_stage1_12);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_12
      if (reset) begin
        holdData_features_stage1_12 <= 14'bx;
      end
      else begin
        holdData_features_stage1_12 <= rawData_features_stage1_12;
      end
    end

  // Data source for features_stage1_13
  initial
    begin : features_stage1_13_fileread
      fp_features_stage1_13 = $fopen("features_stage1_13.dat", "r");
      status_features_stage1_13 = $rewind(fp_features_stage1_13);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_13 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_13 = $fscanf(fp_features_stage1_13, "%h", rawData_features_stage1_13);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_13
      if (reset) begin
        holdData_features_stage1_13 <= 14'bx;
      end
      else begin
        holdData_features_stage1_13 <= rawData_features_stage1_13;
      end
    end

  // Data source for features_stage1_14
  initial
    begin : features_stage1_14_fileread
      fp_features_stage1_14 = $fopen("features_stage1_14.dat", "r");
      status_features_stage1_14 = $rewind(fp_features_stage1_14);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_14 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_14 = $fscanf(fp_features_stage1_14, "%h", rawData_features_stage1_14);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_14
      if (reset) begin
        holdData_features_stage1_14 <= 14'bx;
      end
      else begin
        holdData_features_stage1_14 <= rawData_features_stage1_14;
      end
    end

  // Data source for features_stage1_15
  initial
    begin : features_stage1_15_fileread
      fp_features_stage1_15 = $fopen("features_stage1_15.dat", "r");
      status_features_stage1_15 = $rewind(fp_features_stage1_15);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_15 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_15 = $fscanf(fp_features_stage1_15, "%h", rawData_features_stage1_15);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_15
      if (reset) begin
        holdData_features_stage1_15 <= 14'bx;
      end
      else begin
        holdData_features_stage1_15 <= rawData_features_stage1_15;
      end
    end

  // Data source for features_stage1_16
  initial
    begin : features_stage1_16_fileread
      fp_features_stage1_16 = $fopen("features_stage1_16.dat", "r");
      status_features_stage1_16 = $rewind(fp_features_stage1_16);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_16 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_16 = $fscanf(fp_features_stage1_16, "%h", rawData_features_stage1_16);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_16
      if (reset) begin
        holdData_features_stage1_16 <= 14'bx;
      end
      else begin
        holdData_features_stage1_16 <= rawData_features_stage1_16;
      end
    end

  // Data source for features_stage1_17
  initial
    begin : features_stage1_17_fileread
      fp_features_stage1_17 = $fopen("features_stage1_17.dat", "r");
      status_features_stage1_17 = $rewind(fp_features_stage1_17);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_17 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_17 = $fscanf(fp_features_stage1_17, "%h", rawData_features_stage1_17);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_17
      if (reset) begin
        holdData_features_stage1_17 <= 14'bx;
      end
      else begin
        holdData_features_stage1_17 <= rawData_features_stage1_17;
      end
    end

  // Data source for features_stage1_18
  initial
    begin : features_stage1_18_fileread
      fp_features_stage1_18 = $fopen("features_stage1_18.dat", "r");
      status_features_stage1_18 = $rewind(fp_features_stage1_18);
    end

  always @(features_stage1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage1_18 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage1_18 = $fscanf(fp_features_stage1_18, "%h", rawData_features_stage1_18);
      end
    end

  // holdData reg for features_stage1
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage1_18
      if (reset) begin
        holdData_features_stage1_18 <= 14'bx;
      end
      else begin
        holdData_features_stage1_18 <= rawData_features_stage1_18;
      end
    end

  assign #1 features_stage2_addr_delay_1 = features_stage1_addr;

  // Data source for features_stage2_0
  initial
    begin : features_stage2_0_fileread
      fp_features_stage2_0 = $fopen("features_stage2_0.dat", "r");
      status_features_stage2_0 = $rewind(fp_features_stage2_0);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_0 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_0 = $fscanf(fp_features_stage2_0, "%h", rawData_features_stage2_0);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2
      if (reset) begin
        holdData_features_stage2_0 <= 14'bx;
      end
      else begin
        holdData_features_stage2_0 <= rawData_features_stage2_0;
      end
    end

  // Data source for features_stage2_1
  initial
    begin : features_stage2_1_fileread
      fp_features_stage2_1 = $fopen("features_stage2_1.dat", "r");
      status_features_stage2_1 = $rewind(fp_features_stage2_1);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_1 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_1 = $fscanf(fp_features_stage2_1, "%h", rawData_features_stage2_1);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_1
      if (reset) begin
        holdData_features_stage2_1 <= 14'bx;
      end
      else begin
        holdData_features_stage2_1 <= rawData_features_stage2_1;
      end
    end

  // Data source for features_stage2_2
  initial
    begin : features_stage2_2_fileread
      fp_features_stage2_2 = $fopen("features_stage2_2.dat", "r");
      status_features_stage2_2 = $rewind(fp_features_stage2_2);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_2 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_2 = $fscanf(fp_features_stage2_2, "%h", rawData_features_stage2_2);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_2
      if (reset) begin
        holdData_features_stage2_2 <= 14'bx;
      end
      else begin
        holdData_features_stage2_2 <= rawData_features_stage2_2;
      end
    end

  // Data source for features_stage2_3
  initial
    begin : features_stage2_3_fileread
      fp_features_stage2_3 = $fopen("features_stage2_3.dat", "r");
      status_features_stage2_3 = $rewind(fp_features_stage2_3);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_3 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_3 = $fscanf(fp_features_stage2_3, "%h", rawData_features_stage2_3);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_3
      if (reset) begin
        holdData_features_stage2_3 <= 14'bx;
      end
      else begin
        holdData_features_stage2_3 <= rawData_features_stage2_3;
      end
    end

  // Data source for features_stage2_4
  initial
    begin : features_stage2_4_fileread
      fp_features_stage2_4 = $fopen("features_stage2_4.dat", "r");
      status_features_stage2_4 = $rewind(fp_features_stage2_4);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_4 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_4 = $fscanf(fp_features_stage2_4, "%h", rawData_features_stage2_4);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_4
      if (reset) begin
        holdData_features_stage2_4 <= 14'bx;
      end
      else begin
        holdData_features_stage2_4 <= rawData_features_stage2_4;
      end
    end

  // Data source for features_stage2_5
  initial
    begin : features_stage2_5_fileread
      fp_features_stage2_5 = $fopen("features_stage2_5.dat", "r");
      status_features_stage2_5 = $rewind(fp_features_stage2_5);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_5 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_5 = $fscanf(fp_features_stage2_5, "%h", rawData_features_stage2_5);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_5
      if (reset) begin
        holdData_features_stage2_5 <= 14'bx;
      end
      else begin
        holdData_features_stage2_5 <= rawData_features_stage2_5;
      end
    end

  // Data source for features_stage2_6
  initial
    begin : features_stage2_6_fileread
      fp_features_stage2_6 = $fopen("features_stage2_6.dat", "r");
      status_features_stage2_6 = $rewind(fp_features_stage2_6);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_6 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_6 = $fscanf(fp_features_stage2_6, "%h", rawData_features_stage2_6);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_6
      if (reset) begin
        holdData_features_stage2_6 <= 14'bx;
      end
      else begin
        holdData_features_stage2_6 <= rawData_features_stage2_6;
      end
    end

  // Data source for features_stage2_7
  initial
    begin : features_stage2_7_fileread
      fp_features_stage2_7 = $fopen("features_stage2_7.dat", "r");
      status_features_stage2_7 = $rewind(fp_features_stage2_7);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_7 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_7 = $fscanf(fp_features_stage2_7, "%h", rawData_features_stage2_7);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_7
      if (reset) begin
        holdData_features_stage2_7 <= 14'bx;
      end
      else begin
        holdData_features_stage2_7 <= rawData_features_stage2_7;
      end
    end

  // Data source for features_stage2_8
  initial
    begin : features_stage2_8_fileread
      fp_features_stage2_8 = $fopen("features_stage2_8.dat", "r");
      status_features_stage2_8 = $rewind(fp_features_stage2_8);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_8 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_8 = $fscanf(fp_features_stage2_8, "%h", rawData_features_stage2_8);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_8
      if (reset) begin
        holdData_features_stage2_8 <= 14'bx;
      end
      else begin
        holdData_features_stage2_8 <= rawData_features_stage2_8;
      end
    end

  // Data source for features_stage2_9
  initial
    begin : features_stage2_9_fileread
      fp_features_stage2_9 = $fopen("features_stage2_9.dat", "r");
      status_features_stage2_9 = $rewind(fp_features_stage2_9);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_9 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_9 = $fscanf(fp_features_stage2_9, "%h", rawData_features_stage2_9);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_9
      if (reset) begin
        holdData_features_stage2_9 <= 14'bx;
      end
      else begin
        holdData_features_stage2_9 <= rawData_features_stage2_9;
      end
    end

  // Data source for features_stage2_10
  initial
    begin : features_stage2_10_fileread
      fp_features_stage2_10 = $fopen("features_stage2_10.dat", "r");
      status_features_stage2_10 = $rewind(fp_features_stage2_10);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_10 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_10 = $fscanf(fp_features_stage2_10, "%h", rawData_features_stage2_10);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_10
      if (reset) begin
        holdData_features_stage2_10 <= 14'bx;
      end
      else begin
        holdData_features_stage2_10 <= rawData_features_stage2_10;
      end
    end

  // Data source for features_stage2_11
  initial
    begin : features_stage2_11_fileread
      fp_features_stage2_11 = $fopen("features_stage2_11.dat", "r");
      status_features_stage2_11 = $rewind(fp_features_stage2_11);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_11 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_11 = $fscanf(fp_features_stage2_11, "%h", rawData_features_stage2_11);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_11
      if (reset) begin
        holdData_features_stage2_11 <= 14'bx;
      end
      else begin
        holdData_features_stage2_11 <= rawData_features_stage2_11;
      end
    end

  // Data source for features_stage2_12
  initial
    begin : features_stage2_12_fileread
      fp_features_stage2_12 = $fopen("features_stage2_12.dat", "r");
      status_features_stage2_12 = $rewind(fp_features_stage2_12);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_12 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_12 = $fscanf(fp_features_stage2_12, "%h", rawData_features_stage2_12);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_12
      if (reset) begin
        holdData_features_stage2_12 <= 14'bx;
      end
      else begin
        holdData_features_stage2_12 <= rawData_features_stage2_12;
      end
    end

  // Data source for features_stage2_13
  initial
    begin : features_stage2_13_fileread
      fp_features_stage2_13 = $fopen("features_stage2_13.dat", "r");
      status_features_stage2_13 = $rewind(fp_features_stage2_13);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_13 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_13 = $fscanf(fp_features_stage2_13, "%h", rawData_features_stage2_13);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_13
      if (reset) begin
        holdData_features_stage2_13 <= 14'bx;
      end
      else begin
        holdData_features_stage2_13 <= rawData_features_stage2_13;
      end
    end

  // Data source for features_stage2_14
  initial
    begin : features_stage2_14_fileread
      fp_features_stage2_14 = $fopen("features_stage2_14.dat", "r");
      status_features_stage2_14 = $rewind(fp_features_stage2_14);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_14 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_14 = $fscanf(fp_features_stage2_14, "%h", rawData_features_stage2_14);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_14
      if (reset) begin
        holdData_features_stage2_14 <= 14'bx;
      end
      else begin
        holdData_features_stage2_14 <= rawData_features_stage2_14;
      end
    end

  // Data source for features_stage2_15
  initial
    begin : features_stage2_15_fileread
      fp_features_stage2_15 = $fopen("features_stage2_15.dat", "r");
      status_features_stage2_15 = $rewind(fp_features_stage2_15);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_15 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_15 = $fscanf(fp_features_stage2_15, "%h", rawData_features_stage2_15);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_15
      if (reset) begin
        holdData_features_stage2_15 <= 14'bx;
      end
      else begin
        holdData_features_stage2_15 <= rawData_features_stage2_15;
      end
    end

  // Data source for features_stage2_16
  initial
    begin : features_stage2_16_fileread
      fp_features_stage2_16 = $fopen("features_stage2_16.dat", "r");
      status_features_stage2_16 = $rewind(fp_features_stage2_16);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_16 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_16 = $fscanf(fp_features_stage2_16, "%h", rawData_features_stage2_16);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_16
      if (reset) begin
        holdData_features_stage2_16 <= 14'bx;
      end
      else begin
        holdData_features_stage2_16 <= rawData_features_stage2_16;
      end
    end

  // Data source for features_stage2_17
  initial
    begin : features_stage2_17_fileread
      fp_features_stage2_17 = $fopen("features_stage2_17.dat", "r");
      status_features_stage2_17 = $rewind(fp_features_stage2_17);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_17 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_17 = $fscanf(fp_features_stage2_17, "%h", rawData_features_stage2_17);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_17
      if (reset) begin
        holdData_features_stage2_17 <= 14'bx;
      end
      else begin
        holdData_features_stage2_17 <= rawData_features_stage2_17;
      end
    end

  // Data source for features_stage2_18
  initial
    begin : features_stage2_18_fileread
      fp_features_stage2_18 = $fopen("features_stage2_18.dat", "r");
      status_features_stage2_18 = $rewind(fp_features_stage2_18);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_18 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_18 = $fscanf(fp_features_stage2_18, "%h", rawData_features_stage2_18);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_18
      if (reset) begin
        holdData_features_stage2_18 <= 14'bx;
      end
      else begin
        holdData_features_stage2_18 <= rawData_features_stage2_18;
      end
    end

  // Data source for features_stage2_19
  initial
    begin : features_stage2_19_fileread
      fp_features_stage2_19 = $fopen("features_stage2_19.dat", "r");
      status_features_stage2_19 = $rewind(fp_features_stage2_19);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_19 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_19 = $fscanf(fp_features_stage2_19, "%h", rawData_features_stage2_19);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_19
      if (reset) begin
        holdData_features_stage2_19 <= 14'bx;
      end
      else begin
        holdData_features_stage2_19 <= rawData_features_stage2_19;
      end
    end

  // Data source for features_stage2_20
  initial
    begin : features_stage2_20_fileread
      fp_features_stage2_20 = $fopen("features_stage2_20.dat", "r");
      status_features_stage2_20 = $rewind(fp_features_stage2_20);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_20 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_20 = $fscanf(fp_features_stage2_20, "%h", rawData_features_stage2_20);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_20
      if (reset) begin
        holdData_features_stage2_20 <= 14'bx;
      end
      else begin
        holdData_features_stage2_20 <= rawData_features_stage2_20;
      end
    end

  // Data source for features_stage2_21
  initial
    begin : features_stage2_21_fileread
      fp_features_stage2_21 = $fopen("features_stage2_21.dat", "r");
      status_features_stage2_21 = $rewind(fp_features_stage2_21);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_21 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_21 = $fscanf(fp_features_stage2_21, "%h", rawData_features_stage2_21);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_21
      if (reset) begin
        holdData_features_stage2_21 <= 14'bx;
      end
      else begin
        holdData_features_stage2_21 <= rawData_features_stage2_21;
      end
    end

  // Data source for features_stage2_22
  initial
    begin : features_stage2_22_fileread
      fp_features_stage2_22 = $fopen("features_stage2_22.dat", "r");
      status_features_stage2_22 = $rewind(fp_features_stage2_22);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_22 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_22 = $fscanf(fp_features_stage2_22, "%h", rawData_features_stage2_22);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_22
      if (reset) begin
        holdData_features_stage2_22 <= 14'bx;
      end
      else begin
        holdData_features_stage2_22 <= rawData_features_stage2_22;
      end
    end

  // Data source for features_stage2_23
  initial
    begin : features_stage2_23_fileread
      fp_features_stage2_23 = $fopen("features_stage2_23.dat", "r");
      status_features_stage2_23 = $rewind(fp_features_stage2_23);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_23 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_23 = $fscanf(fp_features_stage2_23, "%h", rawData_features_stage2_23);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_23
      if (reset) begin
        holdData_features_stage2_23 <= 14'bx;
      end
      else begin
        holdData_features_stage2_23 <= rawData_features_stage2_23;
      end
    end

  // Data source for features_stage2_24
  initial
    begin : features_stage2_24_fileread
      fp_features_stage2_24 = $fopen("features_stage2_24.dat", "r");
      status_features_stage2_24 = $rewind(fp_features_stage2_24);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_24 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_24 = $fscanf(fp_features_stage2_24, "%h", rawData_features_stage2_24);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_24
      if (reset) begin
        holdData_features_stage2_24 <= 14'bx;
      end
      else begin
        holdData_features_stage2_24 <= rawData_features_stage2_24;
      end
    end

  // Data source for features_stage2_25
  initial
    begin : features_stage2_25_fileread
      fp_features_stage2_25 = $fopen("features_stage2_25.dat", "r");
      status_features_stage2_25 = $rewind(fp_features_stage2_25);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_25 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_25 = $fscanf(fp_features_stage2_25, "%h", rawData_features_stage2_25);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_25
      if (reset) begin
        holdData_features_stage2_25 <= 14'bx;
      end
      else begin
        holdData_features_stage2_25 <= rawData_features_stage2_25;
      end
    end

  // Data source for features_stage2_26
  initial
    begin : features_stage2_26_fileread
      fp_features_stage2_26 = $fopen("features_stage2_26.dat", "r");
      status_features_stage2_26 = $rewind(fp_features_stage2_26);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_26 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_26 = $fscanf(fp_features_stage2_26, "%h", rawData_features_stage2_26);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_26
      if (reset) begin
        holdData_features_stage2_26 <= 14'bx;
      end
      else begin
        holdData_features_stage2_26 <= rawData_features_stage2_26;
      end
    end

  // Data source for features_stage2_27
  initial
    begin : features_stage2_27_fileread
      fp_features_stage2_27 = $fopen("features_stage2_27.dat", "r");
      status_features_stage2_27 = $rewind(fp_features_stage2_27);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_27 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_27 = $fscanf(fp_features_stage2_27, "%h", rawData_features_stage2_27);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_27
      if (reset) begin
        holdData_features_stage2_27 <= 14'bx;
      end
      else begin
        holdData_features_stage2_27 <= rawData_features_stage2_27;
      end
    end

  // Data source for features_stage2_28
  initial
    begin : features_stage2_28_fileread
      fp_features_stage2_28 = $fopen("features_stage2_28.dat", "r");
      status_features_stage2_28 = $rewind(fp_features_stage2_28);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_28 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_28 = $fscanf(fp_features_stage2_28, "%h", rawData_features_stage2_28);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_28
      if (reset) begin
        holdData_features_stage2_28 <= 14'bx;
      end
      else begin
        holdData_features_stage2_28 <= rawData_features_stage2_28;
      end
    end

  // Data source for features_stage2_29
  initial
    begin : features_stage2_29_fileread
      fp_features_stage2_29 = $fopen("features_stage2_29.dat", "r");
      status_features_stage2_29 = $rewind(fp_features_stage2_29);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_29 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_29 = $fscanf(fp_features_stage2_29, "%h", rawData_features_stage2_29);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_29
      if (reset) begin
        holdData_features_stage2_29 <= 14'bx;
      end
      else begin
        holdData_features_stage2_29 <= rawData_features_stage2_29;
      end
    end

  // Data source for features_stage2_30
  initial
    begin : features_stage2_30_fileread
      fp_features_stage2_30 = $fopen("features_stage2_30.dat", "r");
      status_features_stage2_30 = $rewind(fp_features_stage2_30);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_30 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_30 = $fscanf(fp_features_stage2_30, "%h", rawData_features_stage2_30);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_30
      if (reset) begin
        holdData_features_stage2_30 <= 14'bx;
      end
      else begin
        holdData_features_stage2_30 <= rawData_features_stage2_30;
      end
    end

  // Data source for features_stage2_31
  initial
    begin : features_stage2_31_fileread
      fp_features_stage2_31 = $fopen("features_stage2_31.dat", "r");
      status_features_stage2_31 = $rewind(fp_features_stage2_31);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_31 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_31 = $fscanf(fp_features_stage2_31, "%h", rawData_features_stage2_31);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_31
      if (reset) begin
        holdData_features_stage2_31 <= 14'bx;
      end
      else begin
        holdData_features_stage2_31 <= rawData_features_stage2_31;
      end
    end

  // Data source for features_stage2_32
  initial
    begin : features_stage2_32_fileread
      fp_features_stage2_32 = $fopen("features_stage2_32.dat", "r");
      status_features_stage2_32 = $rewind(fp_features_stage2_32);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_32 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_32 = $fscanf(fp_features_stage2_32, "%h", rawData_features_stage2_32);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_32
      if (reset) begin
        holdData_features_stage2_32 <= 14'bx;
      end
      else begin
        holdData_features_stage2_32 <= rawData_features_stage2_32;
      end
    end

  // Data source for features_stage2_33
  initial
    begin : features_stage2_33_fileread
      fp_features_stage2_33 = $fopen("features_stage2_33.dat", "r");
      status_features_stage2_33 = $rewind(fp_features_stage2_33);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_33 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_33 = $fscanf(fp_features_stage2_33, "%h", rawData_features_stage2_33);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_33
      if (reset) begin
        holdData_features_stage2_33 <= 14'bx;
      end
      else begin
        holdData_features_stage2_33 <= rawData_features_stage2_33;
      end
    end

  // Data source for features_stage2_34
  initial
    begin : features_stage2_34_fileread
      fp_features_stage2_34 = $fopen("features_stage2_34.dat", "r");
      status_features_stage2_34 = $rewind(fp_features_stage2_34);
    end

  always @(features_stage2_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_features_stage2_34 <= 14'bx;
      end
      else if (rdEnb == 1) begin
        status_features_stage2_34 = $fscanf(fp_features_stage2_34, "%h", rawData_features_stage2_34);
      end
    end

  // holdData reg for features_stage2
  always @(posedge clk or posedge reset)
    begin : stimuli_features_stage2_34
      if (reset) begin
        holdData_features_stage2_34 <= 14'bx;
      end
      else begin
        holdData_features_stage2_34 <= rawData_features_stage2_34;
      end
    end

  always @(rawData_features_stage1_0 or rdEnb)
    begin : stimuli_features_stage1_19
      if (rdEnb == 1'b0) begin
        features_stage1_0_offset <= holdData_features_stage1_0;
      end
      else begin
        features_stage1_0_offset <= rawData_features_stage1_0;
      end
    end

  assign #2 features_stage1_0 = features_stage1_0_offset;

  always @(rawData_features_stage1_1 or rdEnb)
    begin : stimuli_features_stage1_20
      if (rdEnb == 1'b0) begin
        features_stage1_1_offset <= holdData_features_stage1_1;
      end
      else begin
        features_stage1_1_offset <= rawData_features_stage1_1;
      end
    end

  assign #2 features_stage1_1 = features_stage1_1_offset;

  always @(rawData_features_stage1_2 or rdEnb)
    begin : stimuli_features_stage1_21
      if (rdEnb == 1'b0) begin
        features_stage1_2_offset <= holdData_features_stage1_2;
      end
      else begin
        features_stage1_2_offset <= rawData_features_stage1_2;
      end
    end

  assign #2 features_stage1_2 = features_stage1_2_offset;

  always @(rawData_features_stage1_3 or rdEnb)
    begin : stimuli_features_stage1_22
      if (rdEnb == 1'b0) begin
        features_stage1_3_offset <= holdData_features_stage1_3;
      end
      else begin
        features_stage1_3_offset <= rawData_features_stage1_3;
      end
    end

  assign #2 features_stage1_3 = features_stage1_3_offset;

  always @(rawData_features_stage1_4 or rdEnb)
    begin : stimuli_features_stage1_23
      if (rdEnb == 1'b0) begin
        features_stage1_4_offset <= holdData_features_stage1_4;
      end
      else begin
        features_stage1_4_offset <= rawData_features_stage1_4;
      end
    end

  assign #2 features_stage1_4 = features_stage1_4_offset;

  always @(rawData_features_stage1_5 or rdEnb)
    begin : stimuli_features_stage1_24
      if (rdEnb == 1'b0) begin
        features_stage1_5_offset <= holdData_features_stage1_5;
      end
      else begin
        features_stage1_5_offset <= rawData_features_stage1_5;
      end
    end

  assign #2 features_stage1_5 = features_stage1_5_offset;

  always @(rawData_features_stage1_6 or rdEnb)
    begin : stimuli_features_stage1_25
      if (rdEnb == 1'b0) begin
        features_stage1_6_offset <= holdData_features_stage1_6;
      end
      else begin
        features_stage1_6_offset <= rawData_features_stage1_6;
      end
    end

  assign #2 features_stage1_6 = features_stage1_6_offset;

  always @(rawData_features_stage1_7 or rdEnb)
    begin : stimuli_features_stage1_26
      if (rdEnb == 1'b0) begin
        features_stage1_7_offset <= holdData_features_stage1_7;
      end
      else begin
        features_stage1_7_offset <= rawData_features_stage1_7;
      end
    end

  assign #2 features_stage1_7 = features_stage1_7_offset;

  always @(rawData_features_stage1_8 or rdEnb)
    begin : stimuli_features_stage1_27
      if (rdEnb == 1'b0) begin
        features_stage1_8_offset <= holdData_features_stage1_8;
      end
      else begin
        features_stage1_8_offset <= rawData_features_stage1_8;
      end
    end

  assign #2 features_stage1_8 = features_stage1_8_offset;

  always @(rawData_features_stage1_9 or rdEnb)
    begin : stimuli_features_stage1_28
      if (rdEnb == 1'b0) begin
        features_stage1_9_offset <= holdData_features_stage1_9;
      end
      else begin
        features_stage1_9_offset <= rawData_features_stage1_9;
      end
    end

  assign #2 features_stage1_9 = features_stage1_9_offset;

  always @(rawData_features_stage1_10 or rdEnb)
    begin : stimuli_features_stage1_29
      if (rdEnb == 1'b0) begin
        features_stage1_10_offset <= holdData_features_stage1_10;
      end
      else begin
        features_stage1_10_offset <= rawData_features_stage1_10;
      end
    end

  assign #2 features_stage1_10 = features_stage1_10_offset;

  always @(rawData_features_stage1_11 or rdEnb)
    begin : stimuli_features_stage1_30
      if (rdEnb == 1'b0) begin
        features_stage1_11_offset <= holdData_features_stage1_11;
      end
      else begin
        features_stage1_11_offset <= rawData_features_stage1_11;
      end
    end

  assign #2 features_stage1_11 = features_stage1_11_offset;

  always @(rawData_features_stage1_12 or rdEnb)
    begin : stimuli_features_stage1_31
      if (rdEnb == 1'b0) begin
        features_stage1_12_offset <= holdData_features_stage1_12;
      end
      else begin
        features_stage1_12_offset <= rawData_features_stage1_12;
      end
    end

  assign #2 features_stage1_12 = features_stage1_12_offset;

  always @(rawData_features_stage1_13 or rdEnb)
    begin : stimuli_features_stage1_32
      if (rdEnb == 1'b0) begin
        features_stage1_13_offset <= holdData_features_stage1_13;
      end
      else begin
        features_stage1_13_offset <= rawData_features_stage1_13;
      end
    end

  assign #2 features_stage1_13 = features_stage1_13_offset;

  always @(rawData_features_stage1_14 or rdEnb)
    begin : stimuli_features_stage1_33
      if (rdEnb == 1'b0) begin
        features_stage1_14_offset <= holdData_features_stage1_14;
      end
      else begin
        features_stage1_14_offset <= rawData_features_stage1_14;
      end
    end

  assign #2 features_stage1_14 = features_stage1_14_offset;

  always @(rawData_features_stage1_15 or rdEnb)
    begin : stimuli_features_stage1_34
      if (rdEnb == 1'b0) begin
        features_stage1_15_offset <= holdData_features_stage1_15;
      end
      else begin
        features_stage1_15_offset <= rawData_features_stage1_15;
      end
    end

  assign #2 features_stage1_15 = features_stage1_15_offset;

  always @(rawData_features_stage1_16 or rdEnb)
    begin : stimuli_features_stage1_35
      if (rdEnb == 1'b0) begin
        features_stage1_16_offset <= holdData_features_stage1_16;
      end
      else begin
        features_stage1_16_offset <= rawData_features_stage1_16;
      end
    end

  assign #2 features_stage1_16 = features_stage1_16_offset;

  always @(rawData_features_stage1_17 or rdEnb)
    begin : stimuli_features_stage1_36
      if (rdEnb == 1'b0) begin
        features_stage1_17_offset <= holdData_features_stage1_17;
      end
      else begin
        features_stage1_17_offset <= rawData_features_stage1_17;
      end
    end

  assign #2 features_stage1_17 = features_stage1_17_offset;

  always @(rawData_features_stage1_18 or rdEnb)
    begin : stimuli_features_stage1_37
      if (rdEnb == 1'b0) begin
        features_stage1_18_offset <= holdData_features_stage1_18;
      end
      else begin
        features_stage1_18_offset <= rawData_features_stage1_18;
      end
    end

  assign #2 features_stage1_18 = features_stage1_18_offset;

  always @(rawData_features_stage2_0 or rdEnb)
    begin : stimuli_features_stage2_35
      if (rdEnb == 1'b0) begin
        features_stage2_0_offset <= holdData_features_stage2_0;
      end
      else begin
        features_stage2_0_offset <= rawData_features_stage2_0;
      end
    end

  assign #2 features_stage2_0 = features_stage2_0_offset;

  always @(rawData_features_stage2_1 or rdEnb)
    begin : stimuli_features_stage2_36
      if (rdEnb == 1'b0) begin
        features_stage2_1_offset <= holdData_features_stage2_1;
      end
      else begin
        features_stage2_1_offset <= rawData_features_stage2_1;
      end
    end

  assign #2 features_stage2_1 = features_stage2_1_offset;

  always @(rawData_features_stage2_2 or rdEnb)
    begin : stimuli_features_stage2_37
      if (rdEnb == 1'b0) begin
        features_stage2_2_offset <= holdData_features_stage2_2;
      end
      else begin
        features_stage2_2_offset <= rawData_features_stage2_2;
      end
    end

  assign #2 features_stage2_2 = features_stage2_2_offset;

  always @(rawData_features_stage2_3 or rdEnb)
    begin : stimuli_features_stage2_38
      if (rdEnb == 1'b0) begin
        features_stage2_3_offset <= holdData_features_stage2_3;
      end
      else begin
        features_stage2_3_offset <= rawData_features_stage2_3;
      end
    end

  assign #2 features_stage2_3 = features_stage2_3_offset;

  always @(rawData_features_stage2_4 or rdEnb)
    begin : stimuli_features_stage2_39
      if (rdEnb == 1'b0) begin
        features_stage2_4_offset <= holdData_features_stage2_4;
      end
      else begin
        features_stage2_4_offset <= rawData_features_stage2_4;
      end
    end

  assign #2 features_stage2_4 = features_stage2_4_offset;

  always @(rawData_features_stage2_5 or rdEnb)
    begin : stimuli_features_stage2_40
      if (rdEnb == 1'b0) begin
        features_stage2_5_offset <= holdData_features_stage2_5;
      end
      else begin
        features_stage2_5_offset <= rawData_features_stage2_5;
      end
    end

  assign #2 features_stage2_5 = features_stage2_5_offset;

  always @(rawData_features_stage2_6 or rdEnb)
    begin : stimuli_features_stage2_41
      if (rdEnb == 1'b0) begin
        features_stage2_6_offset <= holdData_features_stage2_6;
      end
      else begin
        features_stage2_6_offset <= rawData_features_stage2_6;
      end
    end

  assign #2 features_stage2_6 = features_stage2_6_offset;

  always @(rawData_features_stage2_7 or rdEnb)
    begin : stimuli_features_stage2_42
      if (rdEnb == 1'b0) begin
        features_stage2_7_offset <= holdData_features_stage2_7;
      end
      else begin
        features_stage2_7_offset <= rawData_features_stage2_7;
      end
    end

  assign #2 features_stage2_7 = features_stage2_7_offset;

  always @(rawData_features_stage2_8 or rdEnb)
    begin : stimuli_features_stage2_43
      if (rdEnb == 1'b0) begin
        features_stage2_8_offset <= holdData_features_stage2_8;
      end
      else begin
        features_stage2_8_offset <= rawData_features_stage2_8;
      end
    end

  assign #2 features_stage2_8 = features_stage2_8_offset;

  always @(rawData_features_stage2_9 or rdEnb)
    begin : stimuli_features_stage2_44
      if (rdEnb == 1'b0) begin
        features_stage2_9_offset <= holdData_features_stage2_9;
      end
      else begin
        features_stage2_9_offset <= rawData_features_stage2_9;
      end
    end

  assign #2 features_stage2_9 = features_stage2_9_offset;

  always @(rawData_features_stage2_10 or rdEnb)
    begin : stimuli_features_stage2_45
      if (rdEnb == 1'b0) begin
        features_stage2_10_offset <= holdData_features_stage2_10;
      end
      else begin
        features_stage2_10_offset <= rawData_features_stage2_10;
      end
    end

  assign #2 features_stage2_10 = features_stage2_10_offset;

  always @(rawData_features_stage2_11 or rdEnb)
    begin : stimuli_features_stage2_46
      if (rdEnb == 1'b0) begin
        features_stage2_11_offset <= holdData_features_stage2_11;
      end
      else begin
        features_stage2_11_offset <= rawData_features_stage2_11;
      end
    end

  assign #2 features_stage2_11 = features_stage2_11_offset;

  always @(rawData_features_stage2_12 or rdEnb)
    begin : stimuli_features_stage2_47
      if (rdEnb == 1'b0) begin
        features_stage2_12_offset <= holdData_features_stage2_12;
      end
      else begin
        features_stage2_12_offset <= rawData_features_stage2_12;
      end
    end

  assign #2 features_stage2_12 = features_stage2_12_offset;

  always @(rawData_features_stage2_13 or rdEnb)
    begin : stimuli_features_stage2_48
      if (rdEnb == 1'b0) begin
        features_stage2_13_offset <= holdData_features_stage2_13;
      end
      else begin
        features_stage2_13_offset <= rawData_features_stage2_13;
      end
    end

  assign #2 features_stage2_13 = features_stage2_13_offset;

  always @(rawData_features_stage2_14 or rdEnb)
    begin : stimuli_features_stage2_49
      if (rdEnb == 1'b0) begin
        features_stage2_14_offset <= holdData_features_stage2_14;
      end
      else begin
        features_stage2_14_offset <= rawData_features_stage2_14;
      end
    end

  assign #2 features_stage2_14 = features_stage2_14_offset;

  always @(rawData_features_stage2_15 or rdEnb)
    begin : stimuli_features_stage2_50
      if (rdEnb == 1'b0) begin
        features_stage2_15_offset <= holdData_features_stage2_15;
      end
      else begin
        features_stage2_15_offset <= rawData_features_stage2_15;
      end
    end

  assign #2 features_stage2_15 = features_stage2_15_offset;

  always @(rawData_features_stage2_16 or rdEnb)
    begin : stimuli_features_stage2_51
      if (rdEnb == 1'b0) begin
        features_stage2_16_offset <= holdData_features_stage2_16;
      end
      else begin
        features_stage2_16_offset <= rawData_features_stage2_16;
      end
    end

  assign #2 features_stage2_16 = features_stage2_16_offset;

  always @(rawData_features_stage2_17 or rdEnb)
    begin : stimuli_features_stage2_52
      if (rdEnb == 1'b0) begin
        features_stage2_17_offset <= holdData_features_stage2_17;
      end
      else begin
        features_stage2_17_offset <= rawData_features_stage2_17;
      end
    end

  assign #2 features_stage2_17 = features_stage2_17_offset;

  always @(rawData_features_stage2_18 or rdEnb)
    begin : stimuli_features_stage2_53
      if (rdEnb == 1'b0) begin
        features_stage2_18_offset <= holdData_features_stage2_18;
      end
      else begin
        features_stage2_18_offset <= rawData_features_stage2_18;
      end
    end

  assign #2 features_stage2_18 = features_stage2_18_offset;

  always @(rawData_features_stage2_19 or rdEnb)
    begin : stimuli_features_stage2_54
      if (rdEnb == 1'b0) begin
        features_stage2_19_offset <= holdData_features_stage2_19;
      end
      else begin
        features_stage2_19_offset <= rawData_features_stage2_19;
      end
    end

  assign #2 features_stage2_19 = features_stage2_19_offset;

  always @(rawData_features_stage2_20 or rdEnb)
    begin : stimuli_features_stage2_55
      if (rdEnb == 1'b0) begin
        features_stage2_20_offset <= holdData_features_stage2_20;
      end
      else begin
        features_stage2_20_offset <= rawData_features_stage2_20;
      end
    end

  assign #2 features_stage2_20 = features_stage2_20_offset;

  always @(rawData_features_stage2_21 or rdEnb)
    begin : stimuli_features_stage2_56
      if (rdEnb == 1'b0) begin
        features_stage2_21_offset <= holdData_features_stage2_21;
      end
      else begin
        features_stage2_21_offset <= rawData_features_stage2_21;
      end
    end

  assign #2 features_stage2_21 = features_stage2_21_offset;

  always @(rawData_features_stage2_22 or rdEnb)
    begin : stimuli_features_stage2_57
      if (rdEnb == 1'b0) begin
        features_stage2_22_offset <= holdData_features_stage2_22;
      end
      else begin
        features_stage2_22_offset <= rawData_features_stage2_22;
      end
    end

  assign #2 features_stage2_22 = features_stage2_22_offset;

  always @(rawData_features_stage2_23 or rdEnb)
    begin : stimuli_features_stage2_58
      if (rdEnb == 1'b0) begin
        features_stage2_23_offset <= holdData_features_stage2_23;
      end
      else begin
        features_stage2_23_offset <= rawData_features_stage2_23;
      end
    end

  assign #2 features_stage2_23 = features_stage2_23_offset;

  always @(rawData_features_stage2_24 or rdEnb)
    begin : stimuli_features_stage2_59
      if (rdEnb == 1'b0) begin
        features_stage2_24_offset <= holdData_features_stage2_24;
      end
      else begin
        features_stage2_24_offset <= rawData_features_stage2_24;
      end
    end

  assign #2 features_stage2_24 = features_stage2_24_offset;

  always @(rawData_features_stage2_25 or rdEnb)
    begin : stimuli_features_stage2_60
      if (rdEnb == 1'b0) begin
        features_stage2_25_offset <= holdData_features_stage2_25;
      end
      else begin
        features_stage2_25_offset <= rawData_features_stage2_25;
      end
    end

  assign #2 features_stage2_25 = features_stage2_25_offset;

  always @(rawData_features_stage2_26 or rdEnb)
    begin : stimuli_features_stage2_61
      if (rdEnb == 1'b0) begin
        features_stage2_26_offset <= holdData_features_stage2_26;
      end
      else begin
        features_stage2_26_offset <= rawData_features_stage2_26;
      end
    end

  assign #2 features_stage2_26 = features_stage2_26_offset;

  always @(rawData_features_stage2_27 or rdEnb)
    begin : stimuli_features_stage2_62
      if (rdEnb == 1'b0) begin
        features_stage2_27_offset <= holdData_features_stage2_27;
      end
      else begin
        features_stage2_27_offset <= rawData_features_stage2_27;
      end
    end

  assign #2 features_stage2_27 = features_stage2_27_offset;

  always @(rawData_features_stage2_28 or rdEnb)
    begin : stimuli_features_stage2_63
      if (rdEnb == 1'b0) begin
        features_stage2_28_offset <= holdData_features_stage2_28;
      end
      else begin
        features_stage2_28_offset <= rawData_features_stage2_28;
      end
    end

  assign #2 features_stage2_28 = features_stage2_28_offset;

  always @(rawData_features_stage2_29 or rdEnb)
    begin : stimuli_features_stage2_64
      if (rdEnb == 1'b0) begin
        features_stage2_29_offset <= holdData_features_stage2_29;
      end
      else begin
        features_stage2_29_offset <= rawData_features_stage2_29;
      end
    end

  assign #2 features_stage2_29 = features_stage2_29_offset;

  always @(rawData_features_stage2_30 or rdEnb)
    begin : stimuli_features_stage2_65
      if (rdEnb == 1'b0) begin
        features_stage2_30_offset <= holdData_features_stage2_30;
      end
      else begin
        features_stage2_30_offset <= rawData_features_stage2_30;
      end
    end

  assign #2 features_stage2_30 = features_stage2_30_offset;

  always @(rawData_features_stage2_31 or rdEnb)
    begin : stimuli_features_stage2_66
      if (rdEnb == 1'b0) begin
        features_stage2_31_offset <= holdData_features_stage2_31;
      end
      else begin
        features_stage2_31_offset <= rawData_features_stage2_31;
      end
    end

  assign #2 features_stage2_31 = features_stage2_31_offset;

  always @(rawData_features_stage2_32 or rdEnb)
    begin : stimuli_features_stage2_67
      if (rdEnb == 1'b0) begin
        features_stage2_32_offset <= holdData_features_stage2_32;
      end
      else begin
        features_stage2_32_offset <= rawData_features_stage2_32;
      end
    end

  assign #2 features_stage2_32 = features_stage2_32_offset;

  always @(rawData_features_stage2_33 or rdEnb)
    begin : stimuli_features_stage2_68
      if (rdEnb == 1'b0) begin
        features_stage2_33_offset <= holdData_features_stage2_33;
      end
      else begin
        features_stage2_33_offset <= rawData_features_stage2_33;
      end
    end

  assign #2 features_stage2_33 = features_stage2_33_offset;

  always @(rawData_features_stage2_34 or rdEnb)
    begin : stimuli_features_stage2_69
      if (rdEnb == 1'b0) begin
        features_stage2_34_offset <= holdData_features_stage2_34;
      end
      else begin
        features_stage2_34_offset <= rawData_features_stage2_34;
      end
    end

  assign #2 features_stage2_34 = features_stage2_34_offset;

  svm_inference_hdl_v2_fixpt u_svm_inference_hdl_v2_fixpt (.features_stage1_0(features_stage1_0),  // ufix14
                                                           .features_stage1_1(features_stage1_1),  // ufix14
                                                           .features_stage1_2(features_stage1_2),  // ufix14
                                                           .features_stage1_3(features_stage1_3),  // ufix14
                                                           .features_stage1_4(features_stage1_4),  // ufix14
                                                           .features_stage1_5(features_stage1_5),  // ufix14
                                                           .features_stage1_6(features_stage1_6),  // ufix14
                                                           .features_stage1_7(features_stage1_7),  // ufix14
                                                           .features_stage1_8(features_stage1_8),  // ufix14
                                                           .features_stage1_9(features_stage1_9),  // ufix14
                                                           .features_stage1_10(features_stage1_10),  // ufix14
                                                           .features_stage1_11(features_stage1_11),  // ufix14
                                                           .features_stage1_12(features_stage1_12),  // ufix14
                                                           .features_stage1_13(features_stage1_13),  // ufix14
                                                           .features_stage1_14(features_stage1_14),  // ufix14
                                                           .features_stage1_15(features_stage1_15),  // ufix14
                                                           .features_stage1_16(features_stage1_16),  // ufix14
                                                           .features_stage1_17(features_stage1_17),  // ufix14
                                                           .features_stage1_18(features_stage1_18),  // ufix14
                                                           .features_stage2_0(features_stage2_0),  // ufix14
                                                           .features_stage2_1(features_stage2_1),  // ufix14
                                                           .features_stage2_2(features_stage2_2),  // ufix14
                                                           .features_stage2_3(features_stage2_3),  // ufix14
                                                           .features_stage2_4(features_stage2_4),  // ufix14
                                                           .features_stage2_5(features_stage2_5),  // ufix14
                                                           .features_stage2_6(features_stage2_6),  // ufix14
                                                           .features_stage2_7(features_stage2_7),  // ufix14
                                                           .features_stage2_8(features_stage2_8),  // ufix14
                                                           .features_stage2_9(features_stage2_9),  // ufix14
                                                           .features_stage2_10(features_stage2_10),  // ufix14
                                                           .features_stage2_11(features_stage2_11),  // ufix14
                                                           .features_stage2_12(features_stage2_12),  // ufix14
                                                           .features_stage2_13(features_stage2_13),  // ufix14
                                                           .features_stage2_14(features_stage2_14),  // ufix14
                                                           .features_stage2_15(features_stage2_15),  // ufix14
                                                           .features_stage2_16(features_stage2_16),  // ufix14
                                                           .features_stage2_17(features_stage2_17),  // ufix14
                                                           .features_stage2_18(features_stage2_18),  // ufix14
                                                           .features_stage2_19(features_stage2_19),  // ufix14
                                                           .features_stage2_20(features_stage2_20),  // ufix14
                                                           .features_stage2_21(features_stage2_21),  // ufix14
                                                           .features_stage2_22(features_stage2_22),  // ufix14
                                                           .features_stage2_23(features_stage2_23),  // ufix14
                                                           .features_stage2_24(features_stage2_24),  // ufix14
                                                           .features_stage2_25(features_stage2_25),  // ufix14
                                                           .features_stage2_26(features_stage2_26),  // ufix14
                                                           .features_stage2_27(features_stage2_27),  // ufix14
                                                           .features_stage2_28(features_stage2_28),  // ufix14
                                                           .features_stage2_29(features_stage2_29),  // ufix14
                                                           .features_stage2_30(features_stage2_30),  // ufix14
                                                           .features_stage2_31(features_stage2_31),  // ufix14
                                                           .features_stage2_32(features_stage2_32),  // ufix14
                                                           .features_stage2_33(features_stage2_33),  // ufix14
                                                           .features_stage2_34(features_stage2_34),  // ufix14
                                                           .contaminated(contaminated_1),  // ufix1
                                                           .family_id(family_id)  // ufix3
                                                           );

  // Data source for contaminated_expected
  assign contaminated_expected_1 = 1'b1;

  assign contaminated_ref = contaminated_expected_1;

  always @(posedge clk or posedge reset)
    begin : contaminated_1_checker
      if (reset == 1'b1) begin
        contaminated_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && contaminated_1 !== contaminated_ref) begin
          contaminated_testFailure <= 1'b1;
          $display("ERROR in contaminated_1 at time %t : Expected '%h' Actual '%h'", $time, contaminated_ref, contaminated_1);
        end
      end
    end

  // Data source for family_id_expected
  assign family_id_expected_1 = 3'b100;

  assign family_id_ref = family_id_expected_1;

  always @(posedge clk or posedge reset)
    begin : family_id_checker
      if (reset == 1'b1) begin
        family_id_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && family_id !== family_id_ref) begin
          family_id_testFailure <= 1'b1;
          $display("ERROR in family_id at time %t : Expected '%h' Actual '%h'", $time, family_id_ref, family_id);
        end
      end
    end

  assign testFailure = contaminated_testFailure | family_id_testFailure;

  always @(posedge clk)
    begin : completed_msg
      if (snkDone == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // svm_inference_hdl_v2_fixpt_tb

