// -------------------------------------------------------------
// 
// File Name: C:\Users\hp\OneDrive\Documents\Mini Project\v4\codegen\svm_inference_hdl_v2\hdlsrc\svm_inference_hdl_v2_fixpt.v
// Created: 2026-02-12 14:52:09
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: svm_inference_hdl_v2_fixpt
// Source Path: svm_inference_hdl_v2_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------
`timescale 1 ns / 1 ns

module svm_inference_hdl_v2_fixpt
          (features_stage1_0,
           features_stage1_1,
           features_stage1_2,
           features_stage1_3,
           features_stage1_4,
           features_stage1_5,
           features_stage1_6,
           features_stage1_7,
           features_stage1_8,
           features_stage1_9,
           features_stage1_10,
           features_stage1_11,
           features_stage1_12,
           features_stage1_13,
           features_stage1_14,
           features_stage1_15,
           features_stage1_16,
           features_stage1_17,
           features_stage1_18,
           features_stage2_0,
           features_stage2_1,
           features_stage2_2,
           features_stage2_3,
           features_stage2_4,
           features_stage2_5,
           features_stage2_6,
           features_stage2_7,
           features_stage2_8,
           features_stage2_9,
           features_stage2_10,
           features_stage2_11,
           features_stage2_12,
           features_stage2_13,
           features_stage2_14,
           features_stage2_15,
           features_stage2_16,
           features_stage2_17,
           features_stage2_18,
           features_stage2_19,
           features_stage2_20,
           features_stage2_21,
           features_stage2_22,
           features_stage2_23,
           features_stage2_24,
           features_stage2_25,
           features_stage2_26,
           features_stage2_27,
           features_stage2_28,
           features_stage2_29,
           features_stage2_30,
           features_stage2_31,
           features_stage2_32,
           features_stage2_33,
           features_stage2_34,
           contaminated,
           family_id);


  input   [13:0] features_stage1_0;  // ufix14
  input   [13:0] features_stage1_1;  // ufix14
  input   [13:0] features_stage1_2;  // ufix14
  input   [13:0] features_stage1_3;  // ufix14
  input   [13:0] features_stage1_4;  // ufix14
  input   [13:0] features_stage1_5;  // ufix14
  input   [13:0] features_stage1_6;  // ufix14
  input   [13:0] features_stage1_7;  // ufix14
  input   [13:0] features_stage1_8;  // ufix14
  input   [13:0] features_stage1_9;  // ufix14
  input   [13:0] features_stage1_10;  // ufix14
  input   [13:0] features_stage1_11;  // ufix14
  input   [13:0] features_stage1_12;  // ufix14
  input   [13:0] features_stage1_13;  // ufix14
  input   [13:0] features_stage1_14;  // ufix14
  input   [13:0] features_stage1_15;  // ufix14
  input   [13:0] features_stage1_16;  // ufix14
  input   [13:0] features_stage1_17;  // ufix14
  input   [13:0] features_stage1_18;  // ufix14
  input   [13:0] features_stage2_0;  // ufix14
  input   [13:0] features_stage2_1;  // ufix14
  input   [13:0] features_stage2_2;  // ufix14
  input   [13:0] features_stage2_3;  // ufix14
  input   [13:0] features_stage2_4;  // ufix14
  input   [13:0] features_stage2_5;  // ufix14
  input   [13:0] features_stage2_6;  // ufix14
  input   [13:0] features_stage2_7;  // ufix14
  input   [13:0] features_stage2_8;  // ufix14
  input   [13:0] features_stage2_9;  // ufix14
  input   [13:0] features_stage2_10;  // ufix14
  input   [13:0] features_stage2_11;  // ufix14
  input   [13:0] features_stage2_12;  // ufix14
  input   [13:0] features_stage2_13;  // ufix14
  input   [13:0] features_stage2_14;  // ufix14
  input   [13:0] features_stage2_15;  // ufix14
  input   [13:0] features_stage2_16;  // ufix14
  input   [13:0] features_stage2_17;  // ufix14
  input   [13:0] features_stage2_18;  // ufix14
  input   [13:0] features_stage2_19;  // ufix14
  input   [13:0] features_stage2_20;  // ufix14
  input   [13:0] features_stage2_21;  // ufix14
  input   [13:0] features_stage2_22;  // ufix14
  input   [13:0] features_stage2_23;  // ufix14
  input   [13:0] features_stage2_24;  // ufix14
  input   [13:0] features_stage2_25;  // ufix14
  input   [13:0] features_stage2_26;  // ufix14
  input   [13:0] features_stage2_27;  // ufix14
  input   [13:0] features_stage2_28;  // ufix14
  input   [13:0] features_stage2_29;  // ufix14
  input   [13:0] features_stage2_30;  // ufix14
  input   [13:0] features_stage2_31;  // ufix14
  input   [13:0] features_stage2_32;  // ufix14
  input   [13:0] features_stage2_33;  // ufix14
  input   [13:0] features_stage2_34;  // ufix14
  output  contaminated;  // ufix1
  output  [2:0] family_id;  // ufix3


  wire [13:0] features_stage1 [0:18];  // ufix14 [19]
  wire [13:0] features_stage2 [0:34];  // ufix14 [35]


  assign features_stage1[0] = features_stage1_0;
  assign features_stage1[1] = features_stage1_1;
  assign features_stage1[2] = features_stage1_2;
  assign features_stage1[3] = features_stage1_3;
  assign features_stage1[4] = features_stage1_4;
  assign features_stage1[5] = features_stage1_5;
  assign features_stage1[6] = features_stage1_6;
  assign features_stage1[7] = features_stage1_7;
  assign features_stage1[8] = features_stage1_8;
  assign features_stage1[9] = features_stage1_9;
  assign features_stage1[10] = features_stage1_10;
  assign features_stage1[11] = features_stage1_11;
  assign features_stage1[12] = features_stage1_12;
  assign features_stage1[13] = features_stage1_13;
  assign features_stage1[14] = features_stage1_14;
  assign features_stage1[15] = features_stage1_15;
  assign features_stage1[16] = features_stage1_16;
  assign features_stage1[17] = features_stage1_17;
  assign features_stage1[18] = features_stage1_18;

  assign features_stage2[0] = features_stage2_0;
  assign features_stage2[1] = features_stage2_1;
  assign features_stage2[2] = features_stage2_2;
  assign features_stage2[3] = features_stage2_3;
  assign features_stage2[4] = features_stage2_4;
  assign features_stage2[5] = features_stage2_5;
  assign features_stage2[6] = features_stage2_6;
  assign features_stage2[7] = features_stage2_7;
  assign features_stage2[8] = features_stage2_8;
  assign features_stage2[9] = features_stage2_9;
  assign features_stage2[10] = features_stage2_10;
  assign features_stage2[11] = features_stage2_11;
  assign features_stage2[12] = features_stage2_12;
  assign features_stage2[13] = features_stage2_13;
  assign features_stage2[14] = features_stage2_14;
  assign features_stage2[15] = features_stage2_15;
  assign features_stage2[16] = features_stage2_16;
  assign features_stage2[17] = features_stage2_17;
  assign features_stage2[18] = features_stage2_18;
  assign features_stage2[19] = features_stage2_19;
  assign features_stage2[20] = features_stage2_20;
  assign features_stage2[21] = features_stage2_21;
  assign features_stage2[22] = features_stage2_22;
  assign features_stage2[23] = features_stage2_23;
  assign features_stage2[24] = features_stage2_24;
  assign features_stage2[25] = features_stage2_25;
  assign features_stage2[26] = features_stage2_26;
  assign features_stage2[27] = features_stage2_27;
  assign features_stage2[28] = features_stage2_28;
  assign features_stage2[29] = features_stage2_29;
  assign features_stage2[30] = features_stage2_30;
  assign features_stage2[31] = features_stage2_31;
  assign features_stage2[32] = features_stage2_32;
  assign features_stage2[33] = features_stage2_33;
  assign features_stage2[34] = features_stage2_34;

  assign contaminated = 1'b1;
  assign family_id = 3'b100;

endmodule

  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //                                                                          %
  //          Generated by MATLAB 25.1 and Fixed-Point Designer 25.1          %
  //                                                                          %
  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //SVM_INFERENCE_HDL_V2 - HDL Coder compatible pesticide classifier
  //
  // CORRECTED VERSION - Uses compile-time constants instead of persistent
  // Generated: 12-Feb-2026
  //
  // Inputs:
  //   features_stage1 - Stage 1 features (19x1) [int16, Q14]
  //   features_stage2 - Stage 2 features (35x1) [int16, Q14]
  //
  // Outputs:
  //   contaminated - 0=clean, 1=contaminated [uint8]
  //   family_id    - Chemical family 1-5 [uint8]
  //
  // Integer arithmetic with Q14 scaling (2^14 = 16384)
  //    %% ============================================
  // STAGE 1: Binary Classifier Weights (scaled by 2^14)
  //    %% ============================================
  // Using coder.const to make these compile-time constants
  // Bias (2.895286 * 2^14)
  //    %% ============================================
  // STAGE 2: Family Classifier Weights (scaled by 2^14)
  //    %% ============================================
  // Family 1: Organophosphate (REPLACE WITH ACTUAL WEIGHTS)
  // -1.530591
  // Family 2: Carbamate (REPLACE WITH ACTUAL WEIGHTS)
  // -1.384029
  // Family 3: Chlorinated (REPLACE WITH ACTUAL WEIGHTS)
  // -1.805949
  // Family 4: Pyrethroid (REPLACE WITH ACTUAL WEIGHTS)
  // -1.207513
  // Family 5: Other (REPLACE WITH ACTUAL WEIGHTS)
  // -2.154551
  //    %% ============================================
  // STAGE 1: Compute binary classification
  //    %% ============================================
  //    %% ============================================
  // STAGE 2: Compute family scores
  //    %% ============================================
  // Family 1
  // Family 2
  // Family 3
  // Family 4
  // Family 5
  //    %% ============================================
  // Find maximum score (argmax)
  //    %% ============================================

